spring:
  datasource:
    url: jdbc:mysql://db:3306/move?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: move
    password: move
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
